version: '2'
services:
  quoter:
    image: sergeinazarov/quoter:latest
    restart:
      always
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS="-XX:+UseContainerSupport"
      - CATALINA_OPTS=""
    networks:
      - spring-cloud-network
    volumes:
      - ./logs:/workspace/logs
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1200M
networks:
  spring-cloud-network:
    driver: bridge


